// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_D3oybvBDnrAJF8iVSeD5f4qmwB2J_DM',
    appId: '1:87410351152:web:7b934d1c86fa4fd1f9a1f5',
    messagingSenderId: '87410351152',
    projectId: 'slugfind-2024',
    authDomain: 'slugfind-2024.firebaseapp.com',
    storageBucket: 'slugfind-2024.appspot.com',
    measurementId: 'G-LCEPENH46M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAY34VEcavy6psyEeGakt7jB-0AP0Snf-w',
    appId: '1:87410351152:android:974400b9baddaec1f9a1f5',
    messagingSenderId: '87410351152',
    projectId: 'slugfind-2024',
    storageBucket: 'slugfind-2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATljAmM6PxYfJXn-RBjj92-fHXob1W3h4',
    appId: '1:87410351152:ios:0b68b010c2f0567af9a1f5',
    messagingSenderId: '87410351152',
    projectId: 'slugfind-2024',
    storageBucket: 'slugfind-2024.appspot.com',
    iosBundleId: 'com.example.slugFindApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATljAmM6PxYfJXn-RBjj92-fHXob1W3h4',
    appId: '1:87410351152:ios:0b68b010c2f0567af9a1f5',
    messagingSenderId: '87410351152',
    projectId: 'slugfind-2024',
    storageBucket: 'slugfind-2024.appspot.com',
    iosBundleId: 'com.example.slugFindApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_D3oybvBDnrAJF8iVSeD5f4qmwB2J_DM',
    appId: '1:87410351152:web:cbb9e09c472511a8f9a1f5',
    messagingSenderId: '87410351152',
    projectId: 'slugfind-2024',
    authDomain: 'slugfind-2024.firebaseapp.com',
    storageBucket: 'slugfind-2024.appspot.com',
    measurementId: 'G-W8BF2Z0DBL',
  );
}
